# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 852)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    border-image: url(resources/bg1.jpg);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c94b34;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.signout_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.signout_button.setMinimumSize(QtCore.QSize(125, 40))
        self.signout_button.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.signout_button.setFont(font)
        self.signout_button.setObjectName("signout_button")
        self.verticalLayout.addWidget(self.signout_button, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(17, 84, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.card_layout2 = QtWidgets.QHBoxLayout()
        self.card_layout2.setObjectName("card_layout2")
        self.label_welcome = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(65)
        font.setBold(True)
        font.setWeight(75)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("")
        self.label_welcome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.card_layout2.addWidget(self.label_welcome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addLayout(self.card_layout2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.card_layout = QtWidgets.QHBoxLayout()
        self.card_layout.setSpacing(100)
        self.card_layout.setObjectName("card_layout")
        self.card_timetable = HoverCard(parent=self.centralwidget)
        self.card_timetable.setMinimumSize(QtCore.QSize(350, 400))
        self.card_timetable.setMaximumSize(QtCore.QSize(250, 350))
        self.card_timetable.setStyleSheet("")
        self.card_timetable.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card_timetable.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card_timetable.setObjectName("card_timetable")
        self.label = QtWidgets.QLabel(parent=self.card_timetable)
        self.label.setGeometry(QtCore.QRect(0, 40, 341, 48))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: black; /* Or black, depending on your vibe! */\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(parent=self.card_timetable)
        self.label_9.setGeometry(QtCore.QRect(90, 170, 171, 171))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("resources/tt.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.card_layout.addWidget(self.card_timetable)
        self.card_attendance = HoverCard(parent=self.centralwidget)
        self.card_attendance.setMinimumSize(QtCore.QSize(350, 400))
        self.card_attendance.setMaximumSize(QtCore.QSize(250, 350))
        self.card_attendance.setStyleSheet("")
        self.card_attendance.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card_attendance.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card_attendance.setObjectName("card_attendance")
        self.label_4 = QtWidgets.QLabel(parent=self.card_attendance)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 321, 48))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: black; /* Or black, depending on your vibe! */\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.card_attendance)
        self.label_7.setGeometry(QtCore.QRect(10, 84, 331, 48))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: black; /* Or black, depending on your vibe! */\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(parent=self.card_attendance)
        self.label_2.setGeometry(QtCore.QRect(100, 180, 161, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("resources/attendance1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.card_layout.addWidget(self.card_attendance)
        self.card_student = HoverCard(parent=self.centralwidget)
        self.card_student.setMinimumSize(QtCore.QSize(350, 400))
        self.card_student.setMaximumSize(QtCore.QSize(250, 350))
        self.card_student.setStyleSheet("")
        self.card_student.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card_student.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card_student.setObjectName("card_student")
        self.label_6 = QtWidgets.QLabel(parent=self.card_student)
        self.label_6.setGeometry(QtCore.QRect(0, 26, 341, 48))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: black; /* Or black, depending on your vibe! */\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.card_student)
        self.label_8.setGeometry(QtCore.QRect(0, 80, 341, 48))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    color: black; /* Or black, depending on your vibe! */\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(parent=self.card_student)
        self.label_11.setGeometry(QtCore.QRect(90, 170, 181, 171))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("resources/student.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.card_layout.addWidget(self.card_student)
        self.verticalLayout.addLayout(self.card_layout)
        spacerItem2 = QtWidgets.QSpacerItem(17, 85, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1304, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signout_button.setText(_translate("MainWindow", "Signout"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome XYZ!"))
        self.label.setText(_translate("MainWindow", "Timetable"))
        self.label_4.setText(_translate("MainWindow", "Self"))
        self.label_7.setText(_translate("MainWindow", "Attendance"))
        self.label_6.setText(_translate("MainWindow", "Student"))
        self.label_8.setText(_translate("MainWindow", "Report"))
from custom_widgets import HoverCard


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
