# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 607)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* 1. A deep, dark background for the whole app */\n"
"QMainWindow {\n"
"    border-image: url(resources/bluebg.jpg);\n"
"}\n"
"\n"
"/* 2. The Frosted Glass Box */\n"
"#login_box {\n"
"    background-color: rgba(255, 255, 255, 0.05); /* 5% white creates the glass */\n"
"    border: 1px solid rgba(255, 255, 255, 0.1);  /* Soft translucent border */\n"
"    border-radius: 20px;                         /* Apple\'s smooth corners */\n"
"}\n"
"\n"
"/* 3. The Inputs */\n"
"QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0.3); /* Dark translucent inputs */\n"
"    border: 1px solid rgba(255, 255, 255, 0.1);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #007AFF; /* Apple Blue glow */\n"
"}\n"
"\n"
"/* 4. The Button */\n"
"QPushButton {\n"
"    background-color: #f59a62;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f08746;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color: white;\n"
"    font-size: 12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.login_box = QtWidgets.QFrame(parent=self.centralwidget)
        self.login_box.setMaximumSize(QtCore.QSize(600, 550))
        self.login_box.setObjectName("login_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.login_box)
        self.verticalLayout.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.login_box)
        self.label_2.setMaximumSize(QtCore.QSize(325, 200))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("resources/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label = QtWidgets.QLabel(parent=self.login_box)
        self.label.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.username_input = QtWidgets.QLineEdit(parent=self.login_box)
        self.username_input.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.username_input.setFont(font)
        self.username_input.setText("")
        self.username_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.password_input = QtWidgets.QLineEdit(parent=self.login_box)
        self.password_input.setMinimumSize(QtCore.QSize(0, 45))
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.show_password_checkbox = QtWidgets.QCheckBox(parent=self.login_box)
        self.show_password_checkbox.setObjectName("show_password_checkbox")
        self.verticalLayout.addWidget(self.show_password_checkbox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(parent=self.login_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setMinimumSize(QtCore.QSize(125, 45))
        self.login_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.login_box, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Portal Login</span></p></body></html>"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.show_password_checkbox.setText(_translate("MainWindow", "Show Password"))
        self.login_button.setText(_translate("MainWindow", "Confirm"))
